name: neurooo
description: A CLI tool to automatically translate Flutter .arb files using Neurooo APIs.
version: 1.0.1
repository: https://github.com/ValentinTaleb/translate_arb_with_neurooo

environment:
  sdk: ^3.10.4

executables:
  neurooo: neurooo

dependencies:
  args: ^2.7.0
  http: ^1.2.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
